[sources.sql_database.credentials]
drivername = "postgresql"
database = ${ORIGIN_DB}"
password = ${ORIGIN_PASS}"
username = "${ORIGIN_USER}"
host = "${ORIGIN_ADDRESS}"
port = 5432

[destination.postgres.credentials]
database = ${TARGET_DB}"
password = ${TARGET_PASS}"
username = "${TARGET_USER}"
host = "${TARGET_ADDRESS}"
port = 5432
connect_timeout = 15